server:
  port: 8082

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: admin

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: dkchevis@gmail.com
    password: Dk7164##@
    port: 587
    subject: Intensao de compra
    to: dkchevi@hotmail.com
    from: dkchevis@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false



