spring:
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: admin

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: <>
    password: <>
    port: 587
    subject: Transacao
    to: <>
    from: <>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

server:
  port: 8082

