server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/intensaobd
    username: root
    password: root
  jpa:
      hibernate:
        ddl-auto: update
  rabbitmq:
    host: rattlesnake.rmq.cloudamqp.com
    username: lmmgtdet
    password: UDlz-IlIELwOH5nLssBj6rx7JtrSWubH
    virtualhost: lmmgtdet


#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: admin