server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/intensaobd
    username: root
    password: root
  jpa:
      hibernate:
        ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: admin


#  rabbitmq:
#    host: localhost
#    port: 15672
#    username: guest
#    password: admin