server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/msproduto
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    data: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: create